### ISSUE TITLE
Mouse lock doesn't work in Safari

### ISSUE THREAD

**Issue by kaiec** [kaiec/EstyJS#2]
Taken over from dmcoles/EstyJs#1

@Kirkman wrote:

> Mouse lock works perfectly for me in Mac Chrome and Mac Firefox, but nothing happens when I click the "lock" button in Mac Safari.

First question of course is if this is actually still the case. Maybe someone can confirm the bug who has a Mac available.

**Comment by Kirkman** [comment]
I tried it tonight and it looks like it works under Safari 17.5 (Sonoma), as well as the much older 12.1.2 (Mojave).

**Comment by kaiec** [comment]
Great, thank you for checking, then we can close this issue.
